services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: secret_manager
      POSTGRES_PASSWORD: secret_manager_demo_password
      POSTGRES_DB: secret_manager
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
